POST http://localhost:8080/api
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
"id": 1,
"username":"pawan",
"password" : "passcode"
}

<> 2020-11-12T025550.415.json
###

POST http://localhost:8080/api
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "id": 2,
  "username":"pawandemo",
  "password" : "passcodedemo"
}

<> 2020-11-12T025723.201.json
####

GET http://localhost:8080/api
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

<> 2020-11-12T025825.200.json
<> 2020-11-12T025816.404.json

####

GET http://localhost:8080/api/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

<> 2020-11-12T025843.200.json

####

PUT http://localhost:8080/api/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "id": 3,
  "username": "pawandemo",
  "password": "passcodedemo"
}

<> 2020-11-12T030001.200.json